import { PrismaClient } from '@prisma/client';

const data = [
  {
    name: 'Monitor LG 24" Full HD',
    sku: 'MON-LG24FHD',
    description: 'Monitor IPS 75Hz, entrada HDMI e VGA',
    price: 899.9,
    cost: 580.0,
    quantity: 12,
    minStock: 3,
    category: 'Monitores',
  },
  {
    name: 'Monitor Samsung 27" QHD',
    sku: 'MON-SAM27Q',
    description: 'Monitor VA 144Hz, FreeSync Premium',
    price: 1899.9,
    cost: 1250.0,
    quantity: 5,
    minStock: 2,
    category: 'Monitores',
  },
  {
    name: 'Teclado Mecânico Redragon K552',
    sku: 'TEC-RDK552',
    description: 'Switch Red, layout ABNT2, RGB',
    price: 249.9,
    cost: 140.0,
    quantity: 23,
    minStock: 5,
    category: 'Periféricos',
  },
  {
    name: 'Teclado Membrane Logitech K120',
    sku: 'TEC-LGK120',
    description: 'Teclado com fio, layout ABNT2',
    price: 89.9,
    cost: 42.0,
    quantity: 40,
    minStock: 10,
    category: 'Periféricos',
  },
  {
    name: 'Mouse Logitech G203',
    sku: 'MOU-LGG203',
    description: 'Mouse com fio, 8000 DPI, RGB',
    price: 149.9,
    cost: 80.0,
    quantity: 31,
    minStock: 8,
    category: 'Periféricos',
  },
  {
    name: 'Mouse Sem Fio Rapoo M100',
    sku: 'MOU-RPM100',
    description: 'Wireless 2.4GHz, 1600 DPI',
    price: 99.9,
    cost: 48.0,
    quantity: 2,
    minStock: 5,
    category: 'Periféricos',
  },
  {
    name: 'Headset HyperX Cloud Stinger',
    sku: 'HDS-HXCS',
    description: 'Drivers 50mm, microfone retrátil',
    price: 299.9,
    cost: 175.0,
    quantity: 8,
    minStock: 3,
    category: 'Áudio',
  },
  {
    name: 'Headset USB Multilaser PH254',
    sku: 'HDS-MLPH254',
    description: 'Entrada USB, microfone omnidirecional',
    price: 79.9,
    cost: 35.0,
    quantity: 0,
    minStock: 5,
    category: 'Áudio',
  },
  {
    name: 'Webcam Logitech C920',
    sku: 'CAM-LGC920',
    description: 'Full HD 1080p 30fps, microfone estéreo',
    price: 599.9,
    cost: 380.0,
    quantity: 4,
    minStock: 2,
    category: 'Câmeras',
  },
  {
    name: 'Webcam Intelbras CAM-720p',
    sku: 'CAM-IB720',
    description: 'HD 720p, plug and play USB',
    price: 149.9,
    cost: 72.0,
    quantity: 15,
    minStock: 4,
    category: 'Câmeras',
  },
  {
    name: 'Cabo HDMI 2.0 2m',
    sku: 'CAB-HDMI2M',
    description: '4K 60Hz, suporte a HDR',
    price: 39.9,
    cost: 14.0,
    quantity: 60,
    minStock: 15,
    category: 'Cabos',
  },
  {
    name: 'Cabo USB-C para USB-A 1m',
    sku: 'CAB-USBC1M',
    description: 'Carga rápida até 60W, dados 480Mbps',
    price: 29.9,
    cost: 10.0,
    quantity: 80,
    minStock: 20,
    category: 'Cabos',
  },
  {
    name: 'Cabo DisplayPort 1.4 1.8m',
    sku: 'CAB-DP14',
    description: '8K 60Hz, trava de segurança',
    price: 69.9,
    cost: 32.0,
    quantity: 18,
    minStock: 5,
    category: 'Cabos',
  },
  {
    name: 'Hub USB 3.0 7 portas Anker',
    sku: 'HUB-ANK7P',
    description: 'Alimentação externa, LED indicador',
    price: 189.9,
    cost: 98.0,
    quantity: 9,
    minStock: 3,
    category: 'Conectividade',
  },
  {
    name: 'Adaptador USB-C para HDMI',
    sku: 'ADP-USBCHDMI',
    description: '4K 30Hz, compatível Thunderbolt 3',
    price: 79.9,
    cost: 34.0,
    quantity: 22,
    minStock: 6,
    category: 'Conectividade',
  },
  {
    name: 'SSD Kingston NV2 500GB',
    sku: 'SSD-KNV2500',
    description: 'M.2 NVMe PCIe 4.0, leitura 3500MB/s',
    price: 299.9,
    cost: 195.0,
    quantity: 11,
    minStock: 3,
    category: 'Armazenamento',
  },
  {
    name: 'SSD Kingston NV2 1TB',
    sku: 'SSD-KNV21TB',
    description: 'M.2 NVMe PCIe 4.0, leitura 3500MB/s',
    price: 499.9,
    cost: 320.0,
    quantity: 7,
    minStock: 2,
    category: 'Armazenamento',
  },
  {
    name: 'HD Externo Seagate 1TB',
    sku: 'HDE-SEA1TB',
    description: 'USB 3.0, compacto, backup automático',
    price: 349.9,
    cost: 210.0,
    quantity: 3,
    minStock: 3,
    category: 'Armazenamento',
  },
  {
    name: 'Memória RAM Kingston 8GB DDR4',
    sku: 'RAM-KG8D4',
    description: '3200MHz, CL22, tensão 1.2V',
    price: 149.9,
    cost: 88.0,
    quantity: 16,
    minStock: 4,
    category: 'Memória',
  },
  {
    name: 'Memória RAM Kingston 16GB DDR4',
    sku: 'RAM-KG16D4',
    description: '3200MHz, CL22, kit 2x8GB',
    price: 279.9,
    cost: 168.0,
    quantity: 1,
    minStock: 4,
    category: 'Memória',
  },
];

export async function seedProducts(prisma: PrismaClient) {
  for (const product of data) {
    await prisma.product.create({ data: product });
  }
  console.log(`  ${data.length} produtos criados.`);
}
